server:
  port: 8082
  servlet:
    context-path: /audit

spring:
  application:
    name: audit-log
  datasource:
    url: "jdbc:postgresql://localhost:5432/mini_bank"
    username: "postgres"
    password: "16102004"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: off
    show-sql: off

jwt:
  signer-key: "rrWfIP6xe4nw9hk4cZiN9jDbx5UWWi80FiQnxu3vwpzOYGGesbOUSUjRRyCL1pe3"
  valid-duration: "600"
  refreshable-duration: "1800"